[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --alluredir=reports/allure-results --clean-alluredir
log_cli = true
log_cli_level = INFO
